### ISSUE TITLE
step using binary weight ?

### ISSUE THREAD

**Issue by Oussamab21** [AgrawalAmey/learning-digital-net#2]
Do you think that using the binary weights during the optimization step will be better or equal in term of performances when you use real (non binarized weights ) ?

#### Edit:
The the weights are initialized with Bernoulli distribution, specifically how initialization with binary weights affect performance.

**Comment by AgrawalAmey** [comment]
Hi! Not sure what are referring as optimization step, do you mean forward pass or backward pass?

**Comment by Oussamab21** [comment]
Hi, I mean the one after the backward pass as it happens in binary connect you get back your stored parameters before binarization then you perform SGD step and then you clip them now my question was in Binary Connect they use normal weights(initialized using default way) for this task but in your case you are using weight that are already binarized using Bernoulli init what do you think about performance difference ? and why did you pick Bernoulli as initialization method ?

**Comment by AgrawalAmey** [comment]
The explanation for initialization strategy can be found in the subsection 2.4 of corresponding paper.

**Comment by Oussamab21** [comment]
I mean why did you keep only few weights to 1:
"In our experiments we find that initialization with success probability (p) anywhere in the range [0.0001,0.04] performs fairly well." ? is having many weight after post binarization set to 1 will affect performances ?

**Comment by AgrawalAmey** [comment]
Consider a single layer network where all the weights are initialized with 1s. The output of tanh activation would be ~1 for all the neurons in the batch, so after performing batch normalization all the activations would become 0, resultantly the gradients will also become 0. Now, since every neuron is acting like a OR gate, we need to carefully pick number of high weights during initialization.
